language: csharp
solution: tdd.sln
install:
  - nuget restore tdd.sln
  - nuget install NUnit.Runners -Version 3.7.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release testing.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe TagsCloudVizualizationTests/bin/Release/TagsCloudVizualization.dll